import { UserInterface } from './types';

export const generatedUsersList: UserInterface[] = [
  {
    "id":"3",
    "first_name":"Mariah",
    "last_name":"Kerluke",
    "gender":"female",
    "dob":"2011-12-14",
    "email":"ronaldo07@example.org",
    "phone":"269.368.3981 x012",
    "website":"http://grant.com/cum-sunt-quidem-eum-hic.html",
    "address":"74477 Cathrine Ramp Apt. 192\nLake Abdielfort, OR 55359-6275",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/3"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/3"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?16130"
      }
    }
  },
  {
    "id":"4",
    "first_name":"Alessandra",
    "last_name":"Ratke",
    "gender":"female",
    "dob":"1973-10-10",
    "email":"glover.nils@example.net",
    "phone":"847-951-2123 x0980",
    "website":"http://mccullough.com/omnis-quia-aut-porro-eligendi-dignissimos-voluptatem",
    "address":"18079 Dibbert Vista Apt. 099\nPricestad, UT 45552-8405",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/4"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/4"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?38978"
      }
    }
  },
  {
    "id":"5",
    "first_name":"Joseph",
    "last_name":"Strosin",
    "gender":"male",
    "dob":"1962-12-06",
    "email":"rodrick16@example.net",
    "phone":"(236) 373-2828 x68198",
    "website":"http://www.rohan.com/commodi-provident-totam-a-qui-itaque-nemo-sit.html",
    "address":"3407 Ollie Drives Apt. 593\nSouth Maximoshire, MI 66613-6297",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/5"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/5"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?64790"
      }
    }
  },
  {
    "id":"6",
    "first_name":"Angelo",
    "last_name":"Lockman",
    "gender":"male",
    "dob":"1989-10-25",
    "email":"gerry.wiegand@example.net",
    "phone":"+1-508-679-0549",
    "website":"http://www.feeney.biz/placeat-sed-reiciendis-aut-perspiciatis-molestiae-consequuntur-cumque-omnis",
    "address":"87683 O'Keefe Squares\nNorth Hunterview, ND 99261",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/6"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/6"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?16034"
      }
    }
  },
  {
    "id":"7",
    "first_name":"Benedict",
    "last_name":"Reichel",
    "gender":"male",
    "dob":"1970-09-22",
    "email":"hheidenreich@example.com",
    "phone":"(426) 753-6814 x0676",
    "website":"https://www.little.biz/voluptates-tenetur-quae-dignissimos-numquam-voluptatem-nobis-consequuntur",
    "address":"851 Dorthy Plain\nPort Gianni, WV 33511",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/7"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/7"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?67757"
      }
    }
  },
  {
    "id":"8",
    "first_name":"Pattie",
    "last_name":"Crona",
    "gender":"female",
    "dob":"1987-06-21",
    "email":"wbogan@example.com",
    "phone":"494.287.1933",
    "website":"http://www.gaylord.net/enim-ut-numquam-et-sit-est",
    "address":"464 Camren Orchard Suite 983\nSouth Lionel, TX 08763",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/8"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/8"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?46911"
      }
    }
  },
  {
    "id":"9",
    "first_name":"Kyler",
    "last_name":"Kohler",
    "gender":"male",
    "dob":"1936-10-10",
    "email":"gaylord.ashley@example.com",
    "phone":"(970) 991-7592",
    "website":"http://dicki.com/ipsam-maiores-consectetur-deserunt-rerum",
    "address":"38967 Burnice Track Apt. 888\nPort Nilsbury, VA 94852",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/9"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/9"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?65995"
      }
    }
  },
  {
    "id":"10",
    "first_name":"Gus",
    "last_name":"Murphy",
    "gender":"male",
    "dob":"1973-10-13",
    "email":"hudson.amparo@example.com",
    "phone":"1-493-528-1796 x106",
    "website":"http://predovic.com/quam-quam-alias-qui-earum",
    "address":"4175 Lon Plains Apt. 399\nSmithhaven, NH 77685-0251",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/10"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/10"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?16077"
      }
    }
  },
  {
    "id":"11",
    "first_name":"Roosevelt",
    "last_name":"Goyette",
    "gender":"male",
    "dob":"2001-04-29",
    "email":"eugenia.bechtelar@example.com",
    "phone":"(397) 664-8103",
    "website":"http://www.waelchi.org/est-illo-modi-et-id-minima",
    "address":"655 Angelina Gardens\nAgustinfurt, VT 47129-3340",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/11"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/11"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?56186"
      }
    }
  },
  {
    "id":"12",
    "first_name":"Eusebio",
    "last_name":"Farrell",
    "gender":"male",
    "dob":"1945-03-17",
    "email":"price.candido@example.net",
    "phone":"364-529-4215 x40219",
    "website":"http://www.kreiger.com/velit-eveniet-veniam-totam-qui-dolorem-placeat-nobis-laboriosam.html",
    "address":"2659 Jonatan Court Suite 169\nNorth Emeliamouth, OH 88145",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/12"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/12"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?81485"
      }
    }
  },
  {
    "id":"13",
    "first_name":"April",
    "last_name":"Cartwright",
    "gender":"female",
    "dob":"1940-07-16",
    "email":"kmueller@example.net",
    "phone":"+1-412-578-5237",
    "website":"http://www.emmerich.com/sunt-aut-voluptatem-tempore-aut-magni-illo-voluptas",
    "address":"1833 Connelly Cliff\nCremintown, KY 09704",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/13"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/13"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?79429"
      }
    }
  },
  {
    "id":"14",
    "first_name":"Breana",
    "last_name":"Becker",
    "gender":"female",
    "dob":"1981-12-17",
    "email":"zdooley@example.com",
    "phone":"695.700.2755 x8315",
    "website":"http://www.renner.com/voluptas-quidem-a-natus-officia-est",
    "address":"4362 Rhea Coves\nHermannburgh, OH 10810-5554",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/14"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/14"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?64223"
      }
    }
  },
  {
    "id":"15",
    "first_name":"Wilhelm",
    "last_name":"Medhurst",
    "gender":"male",
    "dob":"1934-02-23",
    "email":"bailey.fatima@example.net",
    "phone":"(948) 292-4901 x606",
    "website":"http://www.ritchie.com/et-dolor-numquam-sint-ex-magni-sunt-aliquam",
    "address":"48199 Lisette Harbor Apt. 591\nLake Viva, ID 54868",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/15"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/15"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?38318"
      }
    }
  },
  {
    "id":"16",
    "first_name":"Jayne",
    "last_name":"Corkery",
    "gender":"female",
    "dob":"1932-05-18",
    "email":"zechariah.braun@example.com",
    "phone":"(873) 519-5155",
    "website":"http://www.champlin.net/",
    "address":"324 Terry Stravenue\nWest Florenceton, RI 94611-0331",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/16"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/16"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?47005"
      }
    }
  },
  {
    "id":"17",
    "first_name":"Liliana",
    "last_name":"Sanford",
    "gender":"female",
    "dob":"1966-05-28",
    "email":"humberto.brekke@example.com",
    "phone":"1-557-861-2475",
    "website":"https://www.douglas.com/repellendus-aut-velit-in-dicta-accusantium",
    "address":"8181 Marisa Lock Suite 971\nEast Julienfort, NC 77041-1858",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/17"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/17"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?97100"
      }
    }
  },
  {
    "id":"18",
    "first_name":"Freda",
    "last_name":"Batz",
    "gender":"female",
    "dob":"2006-10-05",
    "email":"xschulist@example.com",
    "phone":"248-917-3430 x7077",
    "website":"http://www.durgan.net/facilis-qui-consequatur-iusto-quam",
    "address":"906 Guido Path Suite 370\nWest Emmett, NC 02255",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/18"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/18"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?70920"
      }
    }
  },
  {
    "id":"19",
    "first_name":"Erin",
    "last_name":"Mills",
    "gender":"male",
    "dob":"1968-12-12",
    "email":"niko99@example.com",
    "phone":"(395) 645-9373 x8027",
    "website":"http://www.fisher.com/delectus-perspiciatis-illo-commodi",
    "address":"34032 Douglas Passage Apt. 086\nEast Joshuashire, OR 20419-4821",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/19"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/19"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?73816"
      }
    }
  },
  {
    "id":"20",
    "first_name":"Bettie",
    "last_name":"Bins",
    "gender":"female",
    "dob":"1961-12-08",
    "email":"annabel00@example.net",
    "phone":"1-368-448-7040",
    "website":"http://www.thiel.com/odit-ipsa-blanditiis-quos-sint-quas-velit-inventore",
    "address":"78487 Jensen Courts Suite 192\nLake Macey, RI 64151-0467",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/20"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/20"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?37368"
      }
    }
  },
  {
    "id":"21",
    "first_name":"Grayson",
    "last_name":"Ebert",
    "gender":"male",
    "dob":"1965-03-15",
    "email":"cristobal.batz@example.org",
    "phone":"(638) 552-3852 x6927",
    "website":"http://www.jacobi.info/consectetur-id-aut-necessitatibus-corporis-omnis.html",
    "address":"78906 Elian Mall\nLoniemouth, CO 27645",
    "status":"active",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/21"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/21"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?48480"
      }
    }
  },
  {
    "id":"22",
    "first_name":"Hettie",
    "last_name":"Gaylord",
    "gender":"female",
    "dob":"1980-08-07",
    "email":"hadams@example.com",
    "phone":"806-632-4964 x54263",
    "website":"http://durgan.com/a-voluptatibus-similique-quibusdam-minus-id-qui-itaque-aspernatur",
    "address":"154 Bruen Manors\nMyrtleton, VA 59333",
    "status":"inactive",
    "_links":{
      "self":{
        "href":"https://gorest.co.in/public-api/users/22"
      },
      "edit":{
        "href":"https://gorest.co.in/public-api/users/22"
      },
      "avatar":{
        "href":"https://lorempixel.com/250/250/people/?68750"
      }
    }
  }
] as any;
